name: 'Job Setup'
description: 'Install go, terraform'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.8'
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.2
        terraform_wrapper: false